import type Metadata from "next";
import { Geist, Geist_Mono, Geologica } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header/Header";


const geistSans = Geologica({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased overflow-hidden`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
